// Generated by scripts/generate-state-vocabulary.mjs from the table inside it. Do not edit;
// change the table, run `npm run generate:state-vocabulary` and commit the result.
import QtQuick

QtObject {
  // Portfolio status the daemon reports in `overview.status`.
  readonly property var overviewStates: [
    "active",
    "available",
    "complete",
    "draft",
    "paused",
    "empty"
  ]

  // Agent connection states, in the order the guided setup and the settings cards list them.
  readonly property var agentStates: [
    "notInstalled",
    "notConnected",
    "connecting",
    "connected",
    "newSessionRequired",
    "needsRepair",
    "configurationConflict",
    "unsupportedVersion",
    "unavailable"
  ]
  readonly property var agentStateLabels: ({
    "notInstalled": "Not installed",
    "notConnected": "Not connected",
    "connecting": "Connecting",
    "connected": "Connected",
    "newSessionRequired": "New session required",
    "needsRepair": "Needs repair",
    "configurationConflict": "Configuration conflict",
    "unsupportedVersion": "Unsupported version",
    "unavailable": "Unavailable"
  })
  readonly property var agentLabels: [
    "Not installed",
    "Not connected",
    "Connecting",
    "Connected",
    "New session required",
    "Needs repair",
    "Configuration conflict",
    "Unsupported version",
    "Unavailable"
  ]

  // Synchronization health as `settings/sync` reports it.
  readonly property var syncStates: [
    "disabled",
    "paused",
    "pending",
    "importing",
    "exporting",
    "healthy",
    "unavailable",
    "error",
    "conflict"
  ]
  readonly property var syncStateLabels: ({
    "disabled": "Not configured",
    "paused": "Synchronization paused",
    "pending": "Changes pending",
    "importing": "Importing changes…",
    "exporting": "Exporting changes…",
    "healthy": "Up to date",
    "unavailable": "Shared folder unavailable; local changes are safe",
    "error": "Synchronization needs attention",
    "conflict": "Conflict requires attention"
  })
  readonly property var syncLabels: [
    "Not configured",
    "Synchronization paused",
    "Changes pending",
    "Importing changes…",
    "Exporting changes…",
    "Up to date",
    "Shared folder unavailable; local changes are safe",
    "Synchronization needs attention",
    "Conflict requires attention"
  ]

  // Automatic backup health as `settings/backup` reports it.
  readonly property var backupStates: [
    "disabled",
    "pending",
    "healthy",
    "error"
  ]
  readonly property var backupStateLabels: ({
    "disabled": "Automatic backup is off",
    "pending": "Backup pending",
    "healthy": "Up to date",
    "error": "Backup needs attention"
  })
  readonly property var backupLabels: [
    "Automatic backup is off",
    "Backup pending",
    "Up to date",
    "Backup needs attention"
  ]
}
