// Generated by scripts/generate-state-vocabulary.mjs from the table inside it. Do not edit;
// change the table, run `npm run generate:state-vocabulary` and commit the result.
import Foundation

/// Portfolio status the daemon reports in `overview.status`.
enum OverviewStatus: String, Codable, CaseIterable, Sendable {
  case active
  case available
  case complete
  case draft
  case paused
  case empty
}

/// Agent connection states, in the order the guided setup and the settings cards list them.
enum SetupComponentState: String, Codable, CaseIterable, Sendable {
  case notInstalled
  case notConnected
  case connecting
  case connected
  case newSessionRequired
  case needsRepair
  case configurationConflict
  case unsupportedVersion
  case unavailable

  /// The line the native surfaces show for this state.
  var label: String {
    switch self {
    case .notInstalled: "Not installed"
    case .notConnected: "Not connected"
    case .connecting: "Connecting"
    case .connected: "Connected"
    case .newSessionRequired: "New session required"
    case .needsRepair: "Needs repair"
    case .configurationConflict: "Configuration conflict"
    case .unsupportedVersion: "Unsupported version"
    case .unavailable: "Unavailable"
    }
  }
}

/// Synchronization health as `settings/sync` reports it.
enum SyncHealthState: String, Codable, CaseIterable, Sendable {
  case disabled
  case paused
  case pending
  case importing
  case exporting
  case healthy
  case unavailable
  case error
  case conflict

  /// The line the native surfaces show for this state.
  var label: String {
    switch self {
    case .disabled: "Not configured"
    case .paused: "Synchronization paused"
    case .pending: "Changes pending"
    case .importing: "Importing changes…"
    case .exporting: "Exporting changes…"
    case .healthy: "Up to date"
    case .unavailable: "Shared folder unavailable"
    case .error: "Synchronization needs attention"
    case .conflict: "Conflict requires attention"
    }
  }
}

/// Automatic backup health as `settings/backup` reports it.
enum BackupHealthState: String, Codable, CaseIterable, Sendable {
  case disabled
  case pending
  case healthy
  case error

  /// The line the native surfaces show for this state.
  var label: String {
    switch self {
    case .disabled: "Automatic backup is off"
    case .pending: "Backing up…"
    case .healthy: "Up to date"
    case .error: "Backup needs attention"
    }
  }
}
